param(
  [switch]$SkipWatch,
  [ValidateSet("local","test","qa","prod")]
  [string]$Env = "local",
  [switch]$NoBrowser,
  [switch]$Rebuild
)

$ErrorActionPreference = "Stop"

$root = Resolve-Path (Join-Path $PSScriptRoot "..")
$backendDir = Join-Path $root "backend"
$frontendDir = Join-Path $root "frontend"
$composeFile = Join-Path $root "docker-compose.yml"
$envFile = Join-Path $root ".env"
if ($Env -ne "local") {
  $candidate = Join-Path $root (".env." + $Env)
  if (Test-Path $candidate) {
    $envFile = $candidate
  } else {
    Write-Host "Env file not found: $candidate. Falling back to $envFile"
  }
}

$env:APP_ENV = $Env
$env:ENV_FILE = $envFile
$envFromFile = @{}
if (Test-Path $envFile) {
  foreach ($line in Get-Content $envFile) {
    $trimmed = $line.Trim()
    if ($trimmed -eq "" -or $trimmed.StartsWith("#")) {
      continue
    }
    if ($trimmed -match "^\s*([^=]+?)\s*=\s*(.*)\s*$") {
      $key = $Matches[1].Trim()
      $value = $Matches[2].Trim().Trim("'").Trim('"')
      if ($key -ne "") {
        $envFromFile[$key] = $value
      }
    }
  }
}
if ($envFromFile.ContainsKey("NEXT_PUBLIC_API_URL")) {
  Set-Item -Path ("Env:" + "NEXT_PUBLIC_API_URL") -Value $envFromFile["NEXT_PUBLIC_API_URL"]
} elseif (-not $env:NEXT_PUBLIC_API_URL) {
  Set-Item -Path ("Env:" + "NEXT_PUBLIC_API_URL") -Value "/api"
}
$watcher = Join-Path (Join-Path $root "scripts") "watch_parquets.py"
$python = [System.IO.Path]::Combine($root, ".venv", "Scripts", "python.exe")
if (-not (Test-Path $python)) {
  $python = "python"
}

# Sync NEXT_PUBLIC_* variables into frontend/.env.local so Next dev uses the selected env.
$frontendEnvLocal = Join-Path $frontendDir ".env.local"
$frontendEnvDev = Join-Path $frontendDir ".env.development"
$frontendEnvProd = Join-Path $frontendDir ".env.production"
$publicLines = @()
foreach ($key in $envFromFile.Keys) {
  if ($key.StartsWith("NEXT_PUBLIC_")) {
    $value = $envFromFile[$key]
    $publicLines += "$key=$value"
  }
}
if ($publicLines.Count -gt 0) {
  $content = @("# Auto-generated by start_all.ps1 for $Env") + $publicLines
  if ($Env -eq "prod") {
    Set-Content -Path $frontendEnvProd -Value $content -Encoding ASCII
  } else {
    Set-Content -Path $frontendEnvDev -Value $content -Encoding ASCII
  }
  Set-Content -Path $frontendEnvLocal -Value @("# Auto-generated by start_all.ps1. Use .env.development or .env.production.") -Encoding ASCII
}

Write-Host "Starting Postgres (Docker)..."
Write-Host "APP_ENV=$Env"
Write-Host "ENV_FILE=$envFile"
if (Test-Path $composeFile) {
  if (Test-Path $envFile) {
    & docker compose -f $composeFile --env-file $envFile up -d
  } else {
    & docker compose -f $composeFile up -d
  }
} else {
  Write-Error "docker-compose.yml not found: $composeFile"
  exit 1
}

if ($Rebuild) {
  Write-Host "Rebuilding DuckDB + Postgres caches..."
  $ingestScript = Join-Path (Join-Path $root "scripts") "ingest_to_duckdb.py"
  $syncScript = Join-Path (Join-Path $root "scripts") "sync_duckdb_to_postgres.py"
  $imagesScript = Join-Path (Join-Path $root "scripts") "convert_images_to_png.py"
  $emptyMatchesScript = Join-Path (Join-Path $root "scripts") "create_empty_matches_2026.py"
  if (Test-Path $imagesScript) {
    Write-Host "Converting images to PNG..."
    & $python $imagesScript
  }
  if (Test-Path $emptyMatchesScript) {
    Write-Host "Ensuring empty matches.parquet for 2026..."
    & $python $emptyMatchesScript
  }
  & $python $ingestScript
  & $python $syncScript
}

Write-Host "Starting backend (FastAPI)..."
Start-Process -FilePath $python -WorkingDirectory $backendDir -ArgumentList "-m","uvicorn","app.main:app","--reload","--port","8000"

Write-Host "Starting frontend (Next.js)..."
Start-Process -FilePath "cmd.exe" -WorkingDirectory $frontendDir -ArgumentList "/c","npm run dev"

if (-not $SkipWatch -and (Test-Path $watcher)) {
  Write-Host "Starting parquet watcher..."
  Start-Process -FilePath $python -WorkingDirectory $root -ArgumentList $watcher,"--run-on-start"
} elseif (-not $SkipWatch) {
  Write-Host "Watcher not found at $watcher"
}

Write-Host "All services started."

if (-not $NoBrowser) {
  Start-Process "http://localhost:3000"
}
